server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: esales
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

stripe:
  api:
    key: sk_test_51OgSVtJlpbq6UejmrPbiCAgoactTJVGD2dzdBCahwR5AfsG8Ox2FzWjsV2BR3mDM3y4ADHloSoxn0ZF3kc51hpub00uGijO8HQ
  webhook:
    secret: whsec_2ce22d5f9d5f5de24fc059103035bbf64fd1f618c1c3a7485bd8ab966ac6563a
