services:
  db:
    image: postgres:17-alpine
    container_name: esales_postgres
    environment:
      POSTGRES_USER: esales
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - esales_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - esales
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: ms_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: e-sales
      MONGO_INITDB_ROOT_PASSWORD: e-sales
    networks:
      - esales
    restart: unless-stopped

  mongo-express:
      image: mongo-express
      container_name: ms_mongo_express
      restart: always
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: e-sales
        ME_CONFIG_MONGODB_ADMINPASSWORD: e-sales
        ME_CONFIG_MONGODB_SERVER: mongodb
      networks:
        - esales
      depends_on:
        - mongodb

networks:
  esales:
    driver: bridge

volumes:
  esales_data:
  mongo_data:
